import { makeStyles } from "@material-ui/core/styles";
import Card from "@material-ui/core/Card";
import CardActions from "@material-ui/core/CardActions";
import CardContent from "@material-ui/core/CardContent";
import Button from "@material-ui/core/Button";
import Typography from "@material-ui/core/Typography";
import React, { Component, Fragment } from "react";
import Grid from "@material-ui/core/Grid";

import PropTypes from "prop-types";

//MUI
import withStyles from "@material-ui/core/styles/withStyles";
import Paper from "@material-ui/core/Paper";
import MuiLink from "@material-ui/core/Link";
//import EditDetails from "EditDetails";
import MUIDataTable from "mui-datatables";

const useStyles = makeStyles({
  paper: {
    minWidth: 275,
    margin: 50,
  },
  bullet: {
    display: "inline-block",
    margin: "0 2px",
    transform: "scale(0.8)",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
  },
  pos: {
    marginBottom: 12,
  },
});

//data
const columns = [
  {
    name: "name",
    label: "Name",
    options: {
      filter: false,
      sort: false,
    },
  },
  {
    name: "value_prop",
    label: "Value Proposition",
    options: {
      filter: false,
      sort: false,
    },
  },
  {
    name: "category",
    label: "Category",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "sub_category",
    label: "Sub-category",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "entity_type",
    label: "Entity Type",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "country",
    label: "Country",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "area",
    label: "Area",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "year_founded",
    label: "Year Founded",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "employees",
    label: "Employees",
    options: {
      filter: true,
      sort: false,
    },
  },
  {
    name: "profile",
    label: "Profile",
    options: {
      filter: true,
      filter: false,
      customBodyRender: (value, tableMeta, updateValue) => {
        return <a href={value}>View Profile</a>;
      },
    },
  },
];

//This is where all the data for the datatable goes
const data = [
  {
    name: "Eco-Solid Group",
    value_prop:
      "Our company provides Waste Management and Event Cleanup services which incorporate sustainable practices. We aim to use eco-friendly cleaning products and manage waste in a responsible manner",
    category: "Waste Management",
    sub_category: "Event service",
    entity_type: "For-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2019",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Active Citizen's Movement Pietermaritzburg",
    value_prop:
      "The Active Citizen's Movement Pietermaritzburg is a civil society formation drawn from all communities and promoting active citizenship",
    category: "Social Sustainability",
    sub_category: "Community Development",
    entity_type: "Non-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2018",
    employees: "1 - 10",
    profile: "/company/acmpmb",
  },
  {
    name: "K.V.M Recyclers",
    value_prop: "Saving our planet through recycling ",
    category: "Waste Management",
    sub_category: "Recycling",
    entity_type: "Non-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2010",
    employees: "1 - 10",
    profile: "/company/kvm-recyclers",
  },
  {
    name: "Development and Research Institute for Southern Africa",
    value_prop: "We promote sustainable development, innovation and research",
    category: "Sustainable Development",
    sub_category: "Research",
    entity_type: "For-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2018",
    employees: "1 - 10",
    profile: "/company/drisa",
  },
  {
    name: "Sustainable Tech (Pty) Ltd",
    value_prop: "Sustainable Technology development and application",
    category: "Sustainable Technology",
    sub_category: "Development",
    entity_type: "For-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2017",
    employees: "1 - 10",
    profile: "/company/sustainable-tech",
  },
  {
    name: "The Pyrolysis Group",
    value_prop:
      "Process waste plastics and oils into high-grade fuels or energy",
    category: "Waste Management",
    sub_category: "Waste-to-Energy",
    entity_type: "For-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2018",
    employees: "1 - 10",
    profile: "/company/pyrolysis-group",
  },
  {
    name: "Biko Sivananda harm reduction and seed bank",
    value_prop:
      "Mandated to reduce violent crime. We advocate for policy reform for human rights",
    category: "Social Sustainability",
    sub_category: "Community Development",
    entity_type: "Non-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2015",
    employees: "1 - 10",
    profile: "/company/biko-sivananda",
  },
  {
    name: "The Litterboom Project",
    value_prop:
      "Marine Plastic River Interception through installing River catchments (Litterbooms) and empowering locals in each of our site locations to collect, sort and recycle this ocean bound plastic pollution",
    category: "Waste Management",
    sub_category: "Community Development",
    entity_type: "Non-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2017",
    employees: "20 - 50",
    profile: "/company/litterboom-project",
  },
  {
    name: "Sibayeni Metrofarming",
    value_prop: "Using technology systems to make Farming Easy ",
    category: "Agriculture ",
    sub_category: "Urban Agriculture",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Gauteng",
    year_founded: "2018",
    employees: "1 - 10",
    profile: "/company/sibayeni-metrofarming",
  },
  {
    name: "Swayana (Pty) Ltd ",
    value_prop: "Project developer that commercializes clean tech in Africa",
    category: "Sustainable Technology",
    sub_category: "Development",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Gauteng",
    year_founded: "2016",
    employees: "1 - 10",
    profile: "/company/swayana",
  },
  {
    name: "Operation Songamanzi ",
    value_prop:
      "Our vision is to encourage People to save water in South Africa",
    category: "Water Management",
    sub_category: "Community Development",
    entity_type: "Non-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2018",
    employees: "10 - 20",
    profile: "/company/operation-songamanzi",
  },
  {
    name: "Sustainable Cities Africa",
    value_prop:
      "A social enterprise partnering for an integrated, transformative & sustainable African urban future",
    category: "Social Sustainability",
    sub_category: "Urban Planning",
    entity_type: "Non-profit",
    country: "Botswana",
    area: "Gabarone",
    year_founded: "2015",
    employees: "10 - 20",
    profile: "/company/sustainable-cities-africa",
  },
  {
    name: "Smartner (Pty) Ltd",
    value_prop:
      "We source eco-friendly and sustainable products for businesses to implement",
    category: "Sustainable Products",
    sub_category: "Retail",
    entity_type: "For-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2019",
    employees: "1 - 10",
    profile: "/company/smartner",
  },
  {
    name: "Kudoti",
    value_prop:
      "Digital platform for efficient waste management and recycling in Africa",
    category: "Waste Management",
    sub_category: "Technology",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Gauteng",
    year_founded: "2018",
    employees: "1 - 10",
    profile: "/company/kudoti",
  },
  {
    name: "Jobs4Mzansi",
    value_prop: "South African Digital Platform for freelancing",
    category: "Social Sustainability",
    sub_category: "Unemployment Alleviation",
    entity_type: "For-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2020",
    employees: "1 - 10",
    profile: "/company/jobs4mzansi",
  },
  {
    name: "Social Capital",
    value_prop: "Consulting company aims at facilitating social sustainability",
    category: "Social Sustainability",
    sub_category: "Consulting",
    entity_type: "For-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "2008",
    employees: "1 - 10",
    profile: "/company/socialcapital",
  },
  {
    name: "Greenlight",
    value_prop: "Eco-friendly products for a Greener South Africa",
    category: "Sustainable Products",
    sub_category: "Retail",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Western Cape",
    year_founded: "2016",
    employees: "1 - 10",
    profile: "/company/greenlight",
  },
  {
    name: "#SeaTheBiggerPicture",
    value_prop:
      "An organization focused on coastal environmental education and ocean pollution awareness",
    category: "Waste Management",
    sub_category: "Marine Waste",
    entity_type: "Non-profit",
    country: "South Africa",
    area: "Western Cape",
    year_founded: "2018",
    employees: "1 - 10",
    profile: "/company/seathebiggerpicture",
  },
  {
    name: "Eco Warrior SA",
    value_prop:
      "A supplier of Eco-friendly products, biodegradable products, reusable products, biodegradable packaging and more",
    category: "Sustainable Products",
    sub_category: "Retail",
    entity_type: "Non-profit",
    country: "South Africa",
    area: "Western Cape",
    year_founded: "2012",
    employees: "1 - 10",
    profile: "/company/ecowarriorsa",
  },
  {
    name: "The Compost Kitchen",
    value_prop:
      "We collect organic kitchen waste from households and recycle it into vermicompost and then give it back to the customer at the end of the month",
    category: "Waste Management",
    sub_category: "Organic Waste",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Gauteng",
    year_founded: "2019",
    employees: "1 - 10",
    profile: "/company/thecompostkitchen",
  },
  {
    name: "Biodegradable",
    value_prop:
      "An online mall of Eco companies that will assist you with planet friendly alternatives to those not so eco friendly products",
    category: "Sustainable Products",
    sub_category: "Retail",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Western Cape",
    year_founded: "2012",
    employees: "1 - 10",
    profile: "/company/biodegradable",
  },
  {
    name: "E'Yako Green",
    value_prop:
      "We are passionate about supporting sustainability in South Africa through the creation of local jobs and the up-cycling and recycling of waste into products",
    category: "Sustainable Products",
    sub_category: "Retail",
    entity_type: "For-profit",
    country: "South Africa",
    area: "KwaZulu-Natal",
    year_founded: "-",
    employees: "1 - 10",
    profile: "/company/eyakogreen",
  },
  {
    name: "Regenize",
    value_prop:
      "We provide a residential recycling collection service and reward residents with Remali when they recycle",
    category: "Waste Management",
    sub_category: "Recycling",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Western Cape",
    year_founded: "2016",
    employees: "1 - 10",
    profile: "/company/regenize",
  },
  {
    name: "SolarTurtle",
    value_prop:
      "Micro-utility business platform to empower entrepreneurs using a unique solar battery charging station",
    category: "Renewable Energy",
    sub_category: "Solar",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Western Cape",
    year_founded: "2012",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Savvy Loo",
    value_prop: "Waterless toilet solution",
    category: "Water Management",
    sub_category: "Sanitation",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Gauteng",
    year_founded: "2010",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "MellowCabs",
    value_prop: "Electric-powered minicab service",
    category: "Renewable Energy",
    sub_category: "Transportation",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Western Cape",
    year_founded: "2012",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Spekboom Trading",
    value_prop:
      "Generates blue-chip carbon credits through restoration projects",
    category: "Carbon Capture",
    sub_category: "Ecosystem Restoration",
    entity_type: "For-profit",
    country: "South Africa",
    area: "-",
    year_founded: "-",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Strauss Energy",
    value_prop:
      "Building an integrated photo voltaic roofing tile for residential houses and commercial units",
    category: "Renewable Energy",
    sub_category: "Solar",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "2007",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Afrisol Energy",
    value_prop:
      "Specialises in design, installation and maintenance of biogas digesters",
    category: "Renewable Energy",
    sub_category: "Biogas",
    entity_type: "Non-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "2010",
    employees: "20 - 50",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Boma Safi",
    value_prop:
      "Sells affordable solar products, clean cook stoves and briquettes to rural households",
    category: "Renewable Energy",
    sub_category: "Solar",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "-",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Cobitech Solar",
    value_prop:
      "Provides solar kits on loan to rural poor households for repayment within one year",
    category: "Renewable Energy",
    sub_category: "Solar",
    entity_type: "For-profit",
    country: "Kenya",
    area: "-",
    year_founded: "2010",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Green Pencils",
    value_prop:
      "Sources old newspapers to produce customized pencils and ball pens",
    category: "Waste Management",
    sub_category: "Recycling",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "2012",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Kencoco",
    value_prop:
      "Uses coconut shells, husks and other biomass material to produce charcoal briquettes and sells to households and institutions",
    category: "Waste Management",
    sub_category: "Biofuels",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Mombasa",
    year_founded: "-",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Plexus Energy",
    value_prop: "Distributes off-grid power solutions such solar lighting",
    category: "Renewable Energy",
    sub_category: "Solar",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "2010",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Skynotch Energy Africa",
    value_prop: "Runs a mini-hydro power generation plant",
    category: "Renewable Energy",
    sub_category: "Hydro-Power",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "2012",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "PEG Africa",
    value_prop:
      "Provides asset-based financing for solar assets to consumers who lack both access to reliable electricity and formal banking services. The company provides loans for solar home systems and other useful assets to off-grid households using pay-as-you-go (PAYG) technology",
    category: "Renewable Energy",
    sub_category: "Solar",
    entity_type: "For-profit",
    country: "Ghana",
    area: "Accra",
    year_founded: "2013",
    employees: "200+",
    profile: "/company/eco-solid-group",
  },
  {
    name: "M-KOPA",
    value_prop:
      "M-KOPA Solar is the market leader of ‘pay-as-you-go’ energy for off-grid customers, combining mobile payments with GSM sensor technology to enable the leasing of solar power systems",
    category: "Renewable Energy",
    sub_category: "Solar",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "2011",
    employees: "200+",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Zola Electric",
    value_prop: "Provides affordable, reliable light and energy services",
    category: "Renewable Energy",
    sub_category: "Solar",
    entity_type: "For-profit",
    country: "Netherlands",
    area: "Amsterdam",
    year_founded: "2012",
    employees: "200+",
    profile: "/company/eco-solid-group",
  },
  {
    name: "3BL Enterprises",
    value_prop:
      "Water network management improving access to water infrastructure",
    category: "Water Management",
    sub_category: "Technology",
    entity_type: "For-profit",
    country: "Ethiopia",
    area: "-",
    year_founded: "2014",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "DIGITAPS",
    value_prop: "Using IoT to Provide Clean Water to Africa",
    category: "Water Management",
    sub_category: "Technology",
    entity_type: "For-profit",
    country: "Nigera",
    area: "-",
    year_founded: "-",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "HydroIQ",
    value_prop: "Smart water utility app",
    category: "Water Management",
    sub_category: "Technology",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "2017",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "GezaJozi",
    value_prop: "Electrically-assisted tricycle",
    category: "Renewable Energy",
    sub_category: "Transport",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Gauteng",
    year_founded: "2018",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Baoberry",
    value_prop: "Bio-intelligent solutions for sustainability",
    category: "Environmental Engineering",
    sub_category: "Restoration",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Northwest Province",
    year_founded: "2013",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "PowerOptimal",
    value_prop: "Solar PV power management technology",
    category: "Energy Efficiency",
    sub_category: "Technology",
    entity_type: "For-profit",
    country: "South Africa",
    area: "Western Cape",
    year_founded: "2014",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "Ojay Greene",
    value_prop:
      "An agribusiness that produces and sources fresh fruits and vegetables from smallholder farmers to sell to urban markets in Kenya",
    category: "Sustainable Agriculture",
    sub_category: "Development",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "2014",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
  {
    name: "FuturePump",
    value_prop: "Development of solar-powered irrigation technologies",
    category: "Sustainable Agriculture",
    sub_category: "Solar Technology",
    entity_type: "For-profit",
    country: "Kenya",
    area: "Nairobi",
    year_founded: "2011",
    employees: "1 - 10",
    profile: "/company/eco-solid-group",
  },
];
//End of datatable values

const options = {
  /* filterType: "checkbox",
  download: "false",
  print: "false",
  fixedHeader: "true",
  */
  filter: true,
  filterType: "dropdown",
  responsive: "standard",
  fixedHeader: true,
  fixedSelectColumn: true,
  tableBodyHeight: "400px",
  download: "false",
  print: "false",
  onRowsDelete: false,
};

export default function StaticDataTable() {
  const classes = useStyles();

  return (
    <MUIDataTable title={""} data={data} columns={columns} options={options} />
  );
}
